export const items = [
  { id: 1, name: "Modern Shakshuka", image: "/image/products/Butter-Mushroom-Crepe.jpg", price: 15.0 },
  { id: 2, name: "Ferroro Nutella Crepe", image: "/image/products/Ferroro-Nutella-Crepe.jpg", price: 16.0 },
  { id: 3, name: "Dubia Chocolate Crepe", image: "/image/products/dubia-crepe.jpg", price: 18.0 },
  { id: 4, name: "Crème Brûlée Crepe (cone-style)", image: "/image/products/Creme-Brulee-Crepe.jpg", price: 16.0 },
  { id: 5, name: "Nutella Strawberry Banana Crepe", image: "/image/products/Nutella-Strawberry-Banana-Crepe.jpg", price: 16.0 },
  { id: 6, name: "Strawberry Crepe", image: "/image/products/Strawberry-Crepe.jpg", price: 16.0 },
  { id: 7, name: "Salmon Onigiri", image: "/image/products/Salmon-Onigiri.jpg", price: 17.0 },
  { id: 8, name: "Double Chocolate Cookies", image: "/image/products/Double-Chocolate-Cookies.jpg", price: 6.5 },
  { id: 9, name: "Original Sugarcane", image: "/image/products/Original-Sugarcane.jpg", price: 6.0 },
  { id: 10, name: "Osmanthus Matcha Cloud", image: "/image/products/Osmanthus-Matcha-Cloud.jpg", price: 7.5 },
  { id: 11, name: "Strawberry Delight Souffle", image: "/image/products/Strawberry-Delight-Souffle.jpg", price: 8.0 },
  { id: 12, name: "Mango Souffle", image: "/image/products/Mango-Souffle.jpg", price: 8.0 },
  { id: 13, name: "Chocolate Lava Basque Slice", image: "/image/products/Chocolate-Lava-Basque-Slice.jpg", price: 7.5 },
  { id: 14, name: "Original Slice Basque", image: "/image/products/Original-Slice-Basque.jpg", price: 7.0 },
];
